stages:
  train:
    cmd: python train.py
    deps:
    - data
    - train.py
    outs:
    - model.h5
    live:
      training_metrics:
        summary: true
        html: true
    params:
      - train.seed
      - train.epochs
      - train.batch_size
